package com.elim.mybatisgeneratordemo.mbg.mapper;

import com.elim.mybatisgeneratordemo.mbg.model.TbTest;
import com.elim.mybatisgeneratordemo.mbg.model.TbTestExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TbTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int countByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int deleteByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int insert(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int insertSelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    List<TbTest> selectByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    TbTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbTest record, @Param("example") TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int updateByExample(@Param("record") TbTest record, @Param("example") TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int updateByPrimaryKeySelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbggenerated Sun Nov 29 17:38:58 CST 2020
     */
    int updateByPrimaryKey(TbTest record);
}